name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove Build Files from Main Branch
        run: rm -rf dist/
        
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: ng build --prod
        
      - name: Checkout gh-pages
        run: git checkout gh-pages
        
      - name: Clear gh-pages branch
        run: |
          git rm -rf .
          git commit -m "Clear gh-pages branch" --allow-empty
          git push origin gh-pages
        
      - name: Copy files to gh-pages
        run: |
          cp -r dist/hangman/* .
          git add .
          git commit -m "Update gh-pages" --allow-empty
          git push origin gh-pages
