name: Build and Deploy
on:
  push:
    branches:
      - main  # Use 'main' instead of 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          npm ci
          npm install -g @angular/cli@16.1.7 requires critters@0.0.20

      - name: Build Angular App
        run: ng build --configuration production --aot

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist/hangman
